import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import NotFound from "@/pages/NotFound";
import { Route, Switch } from "wouter";
import ErrorBoundary from "./components/ErrorBoundary";
import { ThemeProvider } from "./contexts/ThemeContext";
import Home from "./pages/Home";
import LandingPage from "./pages/LandingPage";
import Dashboard from "./pages/Dashboard";
import Analyze from "./pages/Analyze";
import History from "./pages/History";
import Mappings from "./pages/Mappings";
import Settings from "./pages/Settings";
import ProductionLinesDashboard from "./pages/ProductionLinesDashboard";
import UserManagement from "./pages/UserManagement";
import ProductManagement from "./pages/ProductManagement";
import SpecificationManagement from "./pages/SpecificationManagement";
import ProductionLineManagement from "./pages/ProductionLineManagement";
import SamplingMethodManagement from "./pages/SamplingMethodManagement";
import SpcPlanManagement from "./pages/SpcPlanManagement";
import EmailNotificationSettings from "./pages/EmailNotificationSettings";
// import RolePermissionManagement from "./pages/RolePermissionManagement"; // Merged into ModulePermissionManagement
import SmtpSettings from "./pages/SmtpSettings";
import SeedDataPage from "./pages/SeedDataPage";
import WorkstationManagement from "./pages/WorkstationManagement";
import MachineManagement from "./pages/MachineManagement";
import ProcessManagement from "./pages/ProcessManagement";
import AuditLogs from "./pages/AuditLogs";
import SpcReport from "./pages/SpcReport";
import DefectManagement from "./pages/DefectManagement";
import DefectStatistics from "./pages/DefectStatistics";
import MachineTypeManagement from "./pages/MachineTypeManagement";
import FixtureManagement from "./pages/FixtureManagement";
import JigManagement from "./pages/JigManagement";
import MultiAnalysis from "./pages/MultiAnalysis";
import ProductionLineComparison from "./pages/ProductionLineComparison";
import About from "./pages/About";
import ApiDocumentation from "@/pages/ApiDocumentation";
import Profile from "./pages/Profile";
import RulesManagement from "./pages/RulesManagement";
import SpcPlanVisualization from "./pages/SpcPlanVisualization";
import SpcVisualizationDetail from "./pages/SpcVisualizationDetail";
import SseNotificationProvider from "./components/SseNotificationProvider";
import WebhookManagement from "./pages/WebhookManagement";
import ReportTemplateManagement from "./pages/ReportTemplateManagement";
import ExportHistory from "./pages/ExportHistory";
import LocalLogin from "./pages/LocalLogin";
import LocalUserManagement from "./pages/LocalUserManagement";
import ChangePassword from "./pages/ChangePassword";
import LicenseActivation from "./pages/LicenseActivation";
import LicenseAdmin from "./pages/LicenseAdmin";
import LoginHistoryPage from "./pages/LoginHistoryPage";
import SystemSetup from "./pages/SystemSetup";
import DatabaseSettings from "./pages/DatabaseSettings";
import CompanyInfo from "./pages/CompanyInfo";
import BackupHistory from "./pages/BackupHistory";
import ConnectionManager from "./pages/ConnectionManager";
import MeasurementStandards from "./pages/MeasurementStandards";
import MeasurementStandardsDashboard from "./pages/MeasurementStandardsDashboard";
import QuickSpcPlan from "./pages/QuickSpcPlan";
import ValidationRulesManagement from "./pages/ValidationRulesManagement";
import CpkComparisonDashboard from "./pages/CpkComparisonDashboard";
import ShiftCpkComparison from "./pages/ShiftCpkComparison";
import ShiftManagerDashboard from "./pages/ShiftManagerDashboard";
import SpcSummaryReport from "./pages/SpcSummaryReport";
import CpkForecastPage from "./pages/CpkForecastPage";
import LicenseManagement from "./pages/LicenseManagement";
import LicenseNotificationReport from "./pages/LicenseNotificationReport";
import LicenseDashboard from "./pages/LicenseDashboard";
import LicenseCustomers from "./pages/LicenseCustomers";
import LicenseRevenue from "./pages/LicenseRevenue";
import LicenseServerSettings from "./pages/LicenseServerSettings";
import LicenseServerDashboard from "./pages/LicenseServerDashboard";
import RealtimeLineDashboard from "./pages/RealtimeLineDashboard";
import RealtimeMachineConfig from "./pages/RealtimeMachineConfig";
import RealtimeHistory from "./pages/RealtimeHistory";
import AlarmThresholdConfig from "./pages/AlarmThresholdConfig";
import MachineOverviewDashboard from "./pages/MachineOverviewDashboard";
import MachineDetailLive from "./pages/MachineDetailLive";
import MachineAreaManagement from "./pages/MachineAreaManagement";
import MachineStatusReport from "./pages/MachineStatusReport";
import OEEDashboard from "./pages/OEEDashboard";
import OEEAnalysisDashboard from "./pages/OEEAnalysisDashboard";
import OEEComparisonDashboard from "./pages/OEEComparisonDashboard";
import MaintenanceDashboard from "./pages/MaintenanceDashboard";
import MachineDetail from "./pages/MachineDetail";
import ExportRealtimeData from "./pages/ExportRealtimeData";
import SparePartsManagement from "./pages/SparePartsManagement";
import OrganizationManagement from "./pages/OrganizationManagement";
import ApprovalWorkflowManagement from "./pages/ApprovalWorkflowManagement";
import ModulePermissionManagement from "./pages/ModulePermissionManagement";
import PendingApprovals from "./pages/PendingApprovals";
import ApprovalReport from "./pages/ApprovalReport";
import SparePartsGuide from "./pages/SparePartsGuide";
import SparePartsCostReport from "./pages/SparePartsCostReport";
import StockMovements from "./pages/StockMovements";
import InventoryCheck from "./pages/InventoryCheck";
import StockReport from "./pages/StockReport";
import PredictiveMaintenance from "./pages/PredictiveMaintenance";
import MMSDataInit from "./pages/MMSDataInit";
import MaintenanceSchedule from "./pages/MaintenanceSchedule";
import AlertThresholdConfig from "./pages/AlertThresholdConfig";
import EquipmentQRLookup from "./pages/EquipmentQRLookup";
import PlantKPIDashboard from "./pages/PlantKPIDashboard";
import PlantKPIDashboardEnhanced from "./pages/PlantKPIDashboardEnhanced";
import MMSDashboard from "./pages/MMSDashboard";
import IoTGatewayConfig from "./pages/IoTGatewayConfig";
import ReportsExport from "./pages/ReportsExport";
import ReportsExportEnhanced from "./pages/ReportsExportEnhanced";
import AlertConfiguration from "./pages/AlertConfiguration";
import AlertConfigurationEnhanced from "./pages/AlertConfigurationEnhanced";
import ScheduledReports from "./pages/ScheduledReports";
import SupervisorDashboard from "./pages/SupervisorDashboard";
import ShiftReportHistory from "./pages/ShiftReportHistory";
import MachineComparison from "./pages/MachineComparison";
import NotificationCenter from "./pages/NotificationCenter";
import ScheduledJobsManagement from "./pages/ScheduledJobsManagement";
import AdvancedAnalytics from "./pages/AdvancedAnalytics";
import ExportReports from "./pages/ExportReports";
import WebSocketEventLog from "./pages/WebSocketEventLog";
import SseEventLog from "./pages/SseEventLog";
import CustomReportBuilder from "./pages/CustomReportBuilder";
import { GlobalKeyboardShortcuts } from "./components/GlobalKeyboardShortcuts";
import RateLimitDashboard from "./pages/RateLimitDashboard";
import NtfAlertConfig from "./pages/NtfAlertConfig";
import NtfComparison from "./pages/NtfComparison";
import NtfDashboard from "./pages/NtfDashboard";
import NotificationSettings from "./pages/NotificationSettings";
import NtfLineDetail from "./pages/NtfLineDetail";
import NtfShiftAnalysis from "./pages/NtfShiftAnalysis";
import NtfProductAnalysis from "./pages/NtfProductAnalysis";
import NtfDepartmentDashboard from "./pages/NtfDepartmentDashboard";
import NtfSupplierAnalysis from "./pages/NtfSupplierAnalysis";
import NtfEnvironmentCorrelation from "./pages/NtfEnvironmentCorrelation";
import EnvironmentAlertConfig from "./pages/EnvironmentAlertConfig";
import NtfCeoDashboard from "./pages/NtfCeoDashboard";
import UnifiedDashboard from "./pages/UnifiedDashboard";
import OeeAlertThresholdSettings from "./pages/OeeAlertThresholdSettings";
import ScheduledReportManagement from "./pages/ScheduledReportManagement";
import MachineIntegrationDashboard from "./pages/MachineIntegrationDashboard";
import OeeWidget from "./pages/OeeWidget";
import OeeWidgetConfig from "./pages/OeeWidgetConfig";
import DatabaseHealthDashboard from "./pages/DatabaseHealthDashboard";
import DatabaseConnectionsSettings from "./pages/DatabaseConnectionsSettings";
import DatabaseConnectionWizard from "./pages/DatabaseConnectionWizard";
import DataMigrationTool from "./pages/DataMigrationTool";
import DataMigrationToolEnhanced from "./pages/DataMigrationToolEnhanced";
import SchemaComparison from "./pages/SchemaComparison";
import DatabaseUnified from "./pages/DatabaseUnified";
import BackupRestore from "./pages/BackupRestore";
import AnomalyDetection from "./pages/AnomalyDetection";
import AppSettings from "./pages/AppSettings";
import QuickAccessManagement from "./pages/QuickAccessManagement";
import AdminMonitoring from "./pages/AdminMonitoring";
import PerformanceTrendsDashboard from "./pages/PerformanceTrendsDashboard";
import SystemHealthDashboard from "./pages/SystemHealthDashboard";
import SecurityDashboard from "./pages/SecurityDashboard";
import IoTDashboard from "./pages/IoTDashboard";
import IotRealtimeDashboard from "./pages/IotRealtimeDashboard";
import AiMlDashboard from "./pages/ai/AiMlDashboard";
import AiDashboard from "./pages/ai/AiDashboard";
import AiSpcAnalysis from "./pages/AiSpcAnalysis";
import AiRootCause from "./pages/ai/AiRootCause";
import AiNaturalLanguage from "./pages/AiNaturalLanguage";
import AiPredictive from "./pages/ai/AiPredictive";
import AiModelTraining from "./pages/AiModelTraining";
import AiAnalyticsDashboard from "./pages/ai/AiAnalyticsDashboard";
import ABTestingManagement from "./pages/ai/ABTestingManagement";
import ModelVersioningPage from "./pages/ai/ModelVersioningPage";
import DataDriftMonitoring from "./pages/ai/DataDriftMonitoring";
import AiMlHealth from "./pages/ai/AiMlHealth";
import AiCorrelationAnalysis from "./pages/ai/AiCorrelationAnalysis";
import AiTrendAnalysis from "./pages/ai/AiTrendAnalysis";
import AiOeeForecast from "./pages/ai/AiOeeForecast";
import AiDefectPrediction from "./pages/ai/AiDefectPrediction";
import AiVisionDefectDetection from "./pages/ai/AiVisionDefectDetection";
import AiYieldOptimization from "./pages/ai/AiYieldOptimization";
import AiReports from "./pages/ai/AiReports";
import AiInsights from "./pages/ai/AiInsights";
import AiTrainingJobs from "./pages/ai/AiTrainingJobs";
import ModelTraining from "./pages/ai/ModelTraining";
import AiModelComparison from "./pages/ai/AiModelComparison";
import AiModelAccuracyDashboard from "./pages/AiModelAccuracyDashboard";
import AiConfig from "./pages/ai/AiConfig";
import AiThresholds from "./pages/ai/AiThresholds";
import PredictiveAlertConfig from "./pages/ai/PredictiveAlertConfig";
import PredictiveAlertDashboard from "./pages/ai/PredictiveAlertDashboard";
import ForecastAccuracyDashboard from "./pages/ai/ForecastAccuracyDashboard";
import AiDataSources from "./pages/ai/AiDataSources";
import AiAuditLogs from "./pages/ai/AiAuditLogs";
import AiAlerts from "./pages/ai/AiAlerts";
import AiPredictions from "./pages/ai/AiPredictions";
import AiPredictionThresholds from "./pages/ai/AiPredictionThresholds";
import AiPredictionHistory from "./pages/ai/AiPredictionHistory";
import ModelVersionComparison from "./pages/ModelVersionComparison";
import CpkForecastingPage from "./pages/ai/CpkForecastingPage";
import DefectDetectionPage from "./pages/ai/DefectDetectionPage";
import FirebasePushSettingsPage from "./pages/ai/FirebasePushSettingsPage";
import CpkComparisonPage from "./pages/ai/CpkComparisonPage";
import AdvancedAnalyticsDashboard from "./pages/AdvancedAnalyticsDashboard";
import NotificationPreferences from "./pages/NotificationPreferences";
import KpiAlertThresholds from "./pages/KpiAlertThresholds";
import WeeklyKpiTrend from "./pages/WeeklyKpiTrend";
import ScheduledKpiReports from "./pages/ScheduledKpiReports";
import KpiThresholdSettings from "./pages/KpiThresholdSettings";
import ScheduledKpiReportsPage from "./pages/ScheduledKpiReportsPage";
import KpiAlertStats from "./pages/KpiAlertStats";
import AlertHistory from "./pages/AlertHistory";
import AlertDashboard from "./pages/AlertDashboard";
import AlertNotificationConfig from "./pages/AlertNotificationConfig";
import MqttConnectionManagement from "./pages/MqttConnectionManagement";
import OpcuaConnectionManagement from "./pages/OpcuaConnectionManagement";
import SensorDashboard from "./pages/SensorDashboard";
import TwilioSettings from "./pages/TwilioSettings";
import SmsConfigSettings from "./pages/SmsConfigSettings";
import PerformanceDropAlertConfig from "./pages/PerformanceDropAlertConfig";
import WebhookSettings from "./pages/WebhookSettings";
import AlertAnalytics from "./pages/AlertAnalytics";
import UnifiedAlertKpiDashboard from "./pages/UnifiedAlertKpiDashboard";
import WebhookHistoryManagement from "./pages/WebhookHistoryManagement";
import UserGuide from "./pages/UserGuide";
import VideoManagement from "./pages/VideoManagement";
import IotMonitoringRealtime from "./pages/iot/IotMonitoringRealtime";
import AiModelPerformance from "./pages/ai/AiModelPerformance";
import CacheMonitoringDashboard from "./pages/CacheMonitoringDashboard";
import TelegramSettings from "./pages/TelegramSettings";
import IoTFloorPlan from "./pages/IoTFloorPlan";
import FloorPlanDesignerPage from "./pages/FloorPlanDesignerPage";
import AlertWebhookSettings from "./pages/AlertWebhookSettings";
import IoTUnifiedDashboard from "./pages/IoTUnifiedDashboard";
import IoTEnhancedDashboard from "./pages/IoTEnhancedDashboard";
import IoTDeviceManagement from "./pages/IoTDeviceManagement";
import IoTProtocolManagement from "./pages/IoTProtocolManagement";
import IoTAlertEscalation from "./pages/IoTAlertEscalation";
import IoTAnalytics from "./pages/IoTAnalytics";
import IoTFirmwareOTA from "./pages/IoTFirmwareOTA";
import IoTFloorPlanIntegration from "./pages/IoTFloorPlanIntegration";
import IoTPredictiveMaintenance from "./pages/IoTPredictiveMaintenance";
import IoTScheduledOTA from "./pages/IoTScheduledOTA";
import IoT3DFloorPlan from "./pages/IoT3DFloorPlan";
import IoTWorkOrders from "./pages/IoTWorkOrders";
import WebhookEscalationPage from "./pages/WebhookEscalationPage";
import LatencyMonitoringPage from "./pages/LatencyMonitoringPage";
import EscalationConfigPage from "./pages/EscalationConfigPage";
import SmsSettings from "./pages/SmsSettings";
import EscalationDashboard from "./pages/EscalationDashboard";
import AutoResolveSettings from "./pages/AutoResolveSettings";
import EscalationWebhookSettings from "./pages/EscalationWebhookSettings";
import EscalationTemplates from "./pages/EscalationTemplates";
import EscalationReports from "./pages/EscalationReports";
import WidgetConfigScreen from "./pages/WidgetConfigScreen";
import SyncDashboard from "./pages/SyncDashboard";
import WidgetPreview from "./pages/WidgetPreview";
import FCMTestPage from "./pages/FCMTestPage";
import ConflictResolutionScreen from "./pages/ConflictResolutionScreen";
import PushNotificationSettings from "./pages/PushNotificationSettings";
import Model3DManagement from "./pages/Model3DManagement";
import WorkOrderNotificationConfig from "./pages/WorkOrderNotificationConfig";
import MttrMtbfReport from "./pages/MttrMtbfReport";
import IotDeviceCrud from "./pages/IotDeviceCrud";
import IotAlarmCrud from "./pages/IotAlarmCrud";

function Router() {
  return (
    <Switch>
      <Route path="/" component={LandingPage} />
      <Route path="/home" component={Home} />
      <Route path="/setup" component={SystemSetup} />
      <Route path="/database-unified" component={DatabaseUnified} />
      <Route path="/database-settings" component={DatabaseSettings} />
      <Route path="/database-health" component={DatabaseHealthDashboard} />
      <Route path="/database-connections" component={DatabaseConnectionsSettings} />
      <Route path="/database-wizard" component={DatabaseConnectionWizard} />
      <Route path="/data-migration" component={DataMigrationTool} />
      <Route path="/data-migration-enhanced" component={DataMigrationToolEnhanced} />
      <Route path="/schema-comparison" component={SchemaComparison} />
      <Route path="/database-setting" component={DatabaseSettings} />
      <Route path="/connection-manager" component={ConnectionManager} />
      <Route path="/company-info" component={CompanyInfo} />
      <Route path="/local-login" component={LocalLogin} />
      <Route path="/change-password" component={ChangePassword} />
      <Route path="/dashboard" component={Dashboard} />
      <Route path="/anomaly-detection" component={AnomalyDetection} />
      <Route path="/production-lines" component={ProductionLinesDashboard} />
      <Route path="/analyze" component={Analyze} />
      <Route path="/history" component={History} />
      <Route path="/mappings" component={Mappings} />
      <Route path="/settings" component={Settings} />
      <Route path="/app-settings" component={AppSettings} />
      <Route path="/quick-access" component={QuickAccessManagement} />
      <Route path="/users" component={UserManagement} />
      <Route path="/local-users" component={LocalUserManagement} />
      <Route path="/products" component={ProductManagement} />
      <Route path="/specifications" component={SpecificationManagement} />
      <Route path="/production-line-management" component={ProductionLineManagement} />
      <Route path="/sampling-methods" component={SamplingMethodManagement} />
      <Route path="/spc-plans" component={SpcPlanManagement} />
      <Route path="/quick-spc-plan" component={QuickSpcPlan} />
      <Route path="/validation-rules" component={ValidationRulesManagement} />
      <Route path="/cpk-comparison" component={CpkComparisonDashboard} />
      <Route path="/shift-cpk-comparison" component={ShiftCpkComparison} />
      <Route path="/cpk-forecast" component={CpkForecastPage} />
      <Route path="/shift-manager" component={ShiftManagerDashboard} />
      <Route path="/kpi-alert-thresholds" component={KpiAlertThresholds} />
      <Route path="/weekly-kpi-trend" component={WeeklyKpiTrend} />
      <Route path="/scheduled-kpi-reports" component={ScheduledKpiReports} />
      <Route path="/kpi-threshold-settings" component={KpiThresholdSettings} />
      <Route path="/scheduled-kpi-reports-management" component={ScheduledKpiReportsPage} />
      <Route path="/kpi-alert-stats" component={KpiAlertStats} />
      <Route path="/alert-history" component={AlertHistory} />
      <Route path="/alert-dashboard" component={AlertDashboard} />
      <Route path="/alert-notification-config" component={AlertNotificationConfig} />
      <Route path="/spc-summary-report" component={SpcSummaryReport} />
      <Route path="/realtime-line" component={RealtimeLineDashboard} />
      <Route path="/realtime-machine-config" component={RealtimeMachineConfig} />
      <Route path="/realtime-history" component={RealtimeHistory} />
      <Route path="/alarm-threshold-config" component={AlarmThresholdConfig} />
      <Route path="/machine-overview" component={MachineOverviewDashboard} />
      <Route path="/machine-detail/:id" component={MachineDetailLive} />
      <Route path="/machine-areas" component={MachineAreaManagement} />
      <Route path="/machine-status-report" component={MachineStatusReport} />
      <Route path="/oee-dashboard" component={OEEDashboard} />
      <Route path="/oee-comparison" component={OEEComparisonDashboard} />
      <Route path="/oee-analysis" component={OEEAnalysisDashboard} />
      <Route path="/unified-dashboard" component={UnifiedDashboard} />
      <Route path="/maintenance-dashboard" component={MaintenanceDashboard} />
      <Route path="/machine/:id" component={MachineDetail} />
      <Route path="/export-realtime" component={ExportRealtimeData} />
      <Route path="/spare-parts" component={SparePartsManagement} />
      <Route path="/organization" component={OrganizationManagement} />
      <Route path="/approval-workflow" component={ApprovalWorkflowManagement} />
      <Route path="/module-permissions" component={ModulePermissionManagement} />
      <Route path="/pending-approvals" component={PendingApprovals} />
      <Route path="/approval-report" component={ApprovalReport} />
      <Route path="/spare-parts-guide" component={SparePartsGuide} />
      <Route path="/spare-parts-cost-report" component={SparePartsCostReport} />
      <Route path="/stock-movements" component={StockMovements} />
      <Route path="/inventory-check" component={InventoryCheck} />
      <Route path="/stock-report" component={StockReport} />
      <Route path="/predictive-maintenance" component={PredictiveMaintenance} />
      <Route path="/maintenance-schedule" component={MaintenanceSchedule} />
      <Route path="/equipment-qr" component={EquipmentQRLookup} />
      <Route path="/plant-kpi" component={PlantKPIDashboard} />
      <Route path="/plant-kpi-enhanced" component={PlantKPIDashboardEnhanced} />
      <Route path="/mms-dashboard" component={MMSDashboard} />
      <Route path="/iot-gateway" component={IoTGatewayConfig} />
      <Route path="/reports-export" component={ReportsExport} />
      <Route path="/reports-export-enhanced" component={ReportsExportEnhanced} />
      <Route path="/alert-config" component={AlertConfiguration} />
      <Route path="/alert-config-enhanced" component={AlertConfigurationEnhanced} />
      <Route path="/oee-alert-thresholds" component={OeeAlertThresholdSettings} />
      <Route path="/scheduled-reports" component={ScheduledReportManagement} />
      <Route path="/machine-integration" component={MachineIntegrationDashboard} />
      <Route path="/embed/oee" component={OeeWidget} />
      <Route path="/embed/oee/:machineId" component={OeeWidget} />
      <Route path="/oee-widget-config" component={OeeWidgetConfig} />
      <Route path="/ntf-config" component={NtfAlertConfig} />
      <Route path="/ntf-comparison" component={NtfComparison} />
      <Route path="/ntf-dashboard" component={NtfDashboard} />
      <Route path="/notification-settings" component={NotificationSettings} />
      <Route path="/ntf-line/:id" component={NtfLineDetail} />
      <Route path="/ntf-shift-analysis" component={NtfShiftAnalysis} />
      <Route path="/ntf-product-analysis" component={NtfProductAnalysis} />
              <Route path="/ntf-department" component={NtfDepartmentDashboard} />
      <Route path="/ntf-supplier-analysis" component={NtfSupplierAnalysis} />
      <Route path="/ntf-environment" component={NtfEnvironmentCorrelation} />
      <Route path="/environment-alerts" component={EnvironmentAlertConfig} />
      <Route path="/ceo-dashboard" component={NtfCeoDashboard} />
      <Route path="/scheduled-reports" component={ScheduledReports} />
      <Route path="/supervisor-dashboard" component={SupervisorDashboard} />
      <Route path="/shift-reports" component={ShiftReportHistory} />
      <Route path="/machine-comparison" component={MachineComparison} />
      <Route path="/notification-center" component={NotificationCenter} />
      <Route path="/scheduled-jobs" component={ScheduledJobsManagement} />
      <Route path="/advanced-analytics" component={AdvancedAnalytics} />
      <Route path="/export-reports" component={ExportReports} />
              <Route path="/websocket-event-log" component={WebSocketEventLog} />
      <Route path="/sse-event-log" component={SseEventLog} />
      <Route path="/mms-data-init" component={MMSDataInit} />
      <Route path="/alert-threshold-config" component={AlertThresholdConfig} />
      <Route path="/email-notifications" component={EmailNotificationSettings} />

      <Route path="/smtp-settings" component={SmtpSettings} />
      <Route path="/seed-data" component={SeedDataPage} />
      <Route path="/defects" component={DefectManagement} />
      <Route path="/defect-statistics" component={DefectStatistics} />
      <Route path="/workstations" component={WorkstationManagement} />
      <Route path="/machines" component={MachineManagement} />
      <Route path="/processes" component={ProcessManagement} />
      <Route path="/audit-logs" component={AuditLogs} />
      <Route path="/spc-report" component={SpcReport} />
      <Route path="/machine-types" component={MachineTypeManagement} />
      <Route path="/fixtures" component={FixtureManagement} />
      <Route path="/jigs" component={JigManagement} />
      <Route path="/multi-analysis" component={MultiAnalysis} />
      <Route path="/line-comparison" component={ProductionLineComparison} />
      <Route path="/about" component={About} />
          <Route path="/api-docs" component={ApiDocumentation} />
      <Route path="/profile" component={Profile} />
      <Route path="/rules" component={RulesManagement} />
      <Route path="/webhooks" component={WebhookManagement} />
      <Route path="/webhook-history" component={WebhookHistoryManagement} />
      <Route path="/report-templates" component={ReportTemplateManagement} />
      <Route path="/export-history" component={ExportHistory} />
      <Route path="/license-activation" component={LicenseActivation} />
      <Route path="/license-admin" component={LicenseAdmin} />
      <Route path="/license-management" component={LicenseManagement} />
      <Route path="/license-notification-report" component={LicenseNotificationReport} />
      <Route path="/license-dashboard" component={LicenseDashboard} />
      <Route path="/license-customers" component={LicenseCustomers} />
      <Route path="/license-revenue" component={LicenseRevenue} />
      <Route path="/license-server-settings" component={LicenseServerSettings} />
      <Route path="/license-server-dashboard" component={LicenseServerDashboard} />
      <Route path="/login-history" component={LoginHistoryPage} />
      <Route path="/backup-history" component={BackupHistory} />
      <Route path="/backup-restore" component={BackupRestore} />
      <Route path="/measurement-standards" component={MeasurementStandards} />
      <Route path="/measurement-standards-dashboard" component={MeasurementStandardsDashboard} />
      <Route path="/spc-visualization" component={SpcPlanVisualization} />
      <Route path="/spc-visualization/:type/:id" component={SpcVisualizationDetail} />
      <Route path="/custom-report-builder" component={CustomReportBuilder} />
      <Route path="/rate-limit-dashboard" component={RateLimitDashboard} />
      <Route path="/admin-monitoring" component={AdminMonitoring} />
      <Route path="/performance-trends" component={PerformanceTrendsDashboard} />
      <Route path="/system-health" component={SystemHealthDashboard} />
      <Route path="/security-dashboard" component={SecurityDashboard} />
      <Route path="/cache-monitoring" component={CacheMonitoringDashboard} />
      <Route path="/iot-dashboard" component={IoTDashboard} />
      <Route path="/iot-realtime-dashboard" component={IotRealtimeDashboard} />
      <Route path="/mqtt-connections" component={MqttConnectionManagement} />
      <Route path="/opcua-connections" component={OpcuaConnectionManagement} />
      <Route path="/sensor-dashboard" component={SensorDashboard} />
      <Route path="/twilio-settings" component={TwilioSettings} />
      <Route path="/sms-config" component={SmsConfigSettings} />
      <Route path="/performance-drop-alert" component={PerformanceDropAlertConfig} />
      <Route path="/webhook-settings" component={WebhookSettings} />
      <Route path="/alert-analytics" component={AlertAnalytics} />
      <Route path="/unified-alert-kpi" component={UnifiedAlertKpiDashboard} />
      <Route path="/ai-ml-dashboard" component={AiMlDashboard} />
      <Route path="/ai-dashboard" component={AiDashboard} />
      <Route path="/ai-spc-analysis" component={AiSpcAnalysis} />
      <Route path="/ai-root-cause" component={AiRootCause} />
      <Route path="/ai-natural-language" component={AiNaturalLanguage} />
      <Route path="/ai-predictive" component={AiPredictive} />
      <Route path="/ai-model-training" component={AiModelTraining} />
      <Route path="/ai-analytics-dashboard" component={AiAnalyticsDashboard} />
      <Route path="/ai-ab-testing" component={ABTestingManagement} />
      <Route path="/ai-model-versioning" component={ModelVersioningPage} />
      <Route path="/ai-data-drift" component={DataDriftMonitoring} />
      <Route path="/ai-ml-health" component={AiMlHealth} />
      <Route path="/ai-correlation" component={AiCorrelationAnalysis} />
      <Route path="/ai-trend-analysis" component={AiTrendAnalysis} />
      <Route path="/ai-oee-forecast" component={AiOeeForecast} />
      <Route path="/ai-defect-prediction" component={AiDefectPrediction} />
      <Route path="/ai-vision-detection" component={AiVisionDefectDetection} />
      <Route path="/ai-yield-optimization" component={AiYieldOptimization} />
      <Route path="/ai-reports" component={AiReports} />
      <Route path="/ai-insights" component={AiInsights} />
      <Route path="/ai-training-jobs" component={AiTrainingJobs} />
      <Route path="/model-training" component={ModelTraining} />
      <Route path="/ai-model-comparison" component={AiModelComparison} />
      <Route path="/ai-model-accuracy" component={AiModelAccuracyDashboard} />
      <Route path="/ai-config" component={AiConfig} />
      <Route path="/ai-thresholds" component={AiThresholds} />
      <Route path="/ai-predictive-alerts" component={PredictiveAlertConfig} />
      <Route path="/ai-predictive-alert-dashboard" component={PredictiveAlertDashboard} />
      <Route path="/ai-forecast-accuracy" component={ForecastAccuracyDashboard} />
      <Route path="/ai-data-sources" component={AiDataSources} />
      <Route path="/ai-audit-logs" component={AiAuditLogs} />
      <Route path="/ai-alerts" component={AiAlerts} />
      <Route path="/ai-predictions" component={AiPredictions} />
      <Route path="/ai-prediction-thresholds" component={AiPredictionThresholds} />
      <Route path="/ai-prediction-history" component={AiPredictionHistory} />
      <Route path="/model-version-comparison" component={ModelVersionComparison} />
      <Route path="/cpk-forecasting" component={CpkForecastingPage} />
      <Route path="/defect-detection" component={DefectDetectionPage} />
      <Route path="/firebase-push-settings" component={FirebasePushSettingsPage} />
      <Route path="/cpk-comparison" component={CpkComparisonPage} />
      <Route path="/advanced-analytics-dashboard" component={AdvancedAnalyticsDashboard} />
      <Route path="/notification-preferences" component={NotificationPreferences} />
      <Route path="/user-guide" component={UserGuide} />
      <Route path="/video-management" component={VideoManagement} />
      <Route path="/iot-monitoring-realtime" component={IotMonitoringRealtime} />
      <Route path="/telegram-settings" component={TelegramSettings} />
      <Route path="/iot-floor-plan" component={IoTFloorPlan} />
      <Route path="/floor-plan-designer" component={FloorPlanDesignerPage} />
      <Route path="/alert-webhook-settings" component={AlertWebhookSettings} />
      <Route path="/iot-unified-dashboard" component={IoTUnifiedDashboard} />
      <Route path="/iot-enhanced-dashboard" component={IoTEnhancedDashboard} />
      <Route path="/iot-device-management" component={IoTDeviceManagement} />
      <Route path="/iot-protocol-management" component={IoTProtocolManagement} />
      <Route path="/iot-alert-escalation" component={IoTAlertEscalation} />
      <Route path="/iot-analytics" component={IoTAnalytics} />
      <Route path="/iot-firmware-ota" component={IoTFirmwareOTA} />
      <Route path="/iot-floor-plan-integration" component={IoTFloorPlanIntegration} />
      <Route path="/iot-predictive-maintenance" component={IoTPredictiveMaintenance} />
      <Route path="/iot-scheduled-ota" component={IoTScheduledOTA} />
      <Route path="/iot-3d-floor-plan" component={IoT3DFloorPlan} />
      <Route path="/iot-work-orders" component={IoTWorkOrders} />
      <Route path="/webhook-escalation" component={WebhookEscalationPage} />
      <Route path="/escalation-config" component={EscalationConfigPage} />
      <Route path="/sms-settings" component={SmsSettings} />
      <Route path="/escalation-dashboard" component={EscalationDashboard} />
      <Route path="/auto-resolve-settings" component={AutoResolveSettings} />
      <Route path="/escalation-webhook-settings" component={EscalationWebhookSettings} />
      <Route path="/escalation-templates" component={EscalationTemplates} />
      <Route path="/escalation-reports" component={EscalationReports} />
      <Route path="/latency-monitoring" component={LatencyMonitoringPage} />
      <Route path="/widget-config" component={WidgetConfigScreen} />
      <Route path="/sync-dashboard" component={SyncDashboard} />
      <Route path="/widget-preview" component={WidgetPreview} />
      <Route path="/fcm-test" component={FCMTestPage} />
      <Route path="/conflict-resolution" component={ConflictResolutionScreen} />
      <Route path="/push-notification-settings" component={PushNotificationSettings} />
      <Route path="/ai-model-performance" component={AiModelPerformance} />
      {/* Phase 98: IoT Enhancement */}
      <Route path="/model-3d-management" component={Model3DManagement} />
      {/* Phase 101: IoT Frontend Management */}
      <Route path="/iot-device-crud" component={IotDeviceCrud} />
      <Route path="/iot-alarm-crud" component={IotAlarmCrud} />
      <Route path="/work-order-notification-config" component={WorkOrderNotificationConfig} />
      <Route path="/mttr-mtbf-report" component={MttrMtbfReport} />
      <Route path="/404" component={NotFound} />
      <Route component={NotFound} />
    </Switch>
  );
}

function App() {
  return (
    <ErrorBoundary>
      <ThemeProvider defaultTheme="light" switchable={true}>
        <TooltipProvider>
          <GlobalKeyboardShortcuts>
            <SseNotificationProvider>
              <Toaster />
              <Router />
            </SseNotificationProvider>
          </GlobalKeyboardShortcuts>
        </TooltipProvider>
      </ThemeProvider>
    </ErrorBoundary>
  );
}

export default App;
