CREATE TABLE `spc_realtime_data` (
	`id` int AUTO_INCREMENT NOT NULL,
	`planId` int NOT NULL,
	`productionLineId` int NOT NULL,
	`mappingId` int,
	`sampleIndex` int NOT NULL,
	`sampleValue` int NOT NULL,
	`subgroupIndex` int NOT NULL,
	`subgroupMean` int,
	`subgroupRange` int,
	`ucl` int,
	`lcl` int,
	`usl` int,
	`lsl` int,
	`centerLine` int,
	`isOutOfSpec` int NOT NULL DEFAULT 0,
	`isOutOfControl` int NOT NULL DEFAULT 0,
	`violatedRules` varchar(100),
	`sampledAt` timestamp NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `spc_realtime_data_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `spc_summary_stats` (
	`id` int AUTO_INCREMENT NOT NULL,
	`planId` int NOT NULL,
	`productionLineId` int NOT NULL,
	`mappingId` int,
	`periodType` enum('shift','day','week','month') NOT NULL,
	`periodStart` timestamp NOT NULL,
	`periodEnd` timestamp NOT NULL,
	`sampleCount` int NOT NULL DEFAULT 0,
	`subgroupCount` int NOT NULL DEFAULT 0,
	`mean` int,
	`stdDev` int,
	`min` int,
	`max` int,
	`range` int,
	`cp` int,
	`cpk` int,
	`pp` int,
	`ppk` int,
	`ca` int,
	`xBarUcl` int,
	`xBarLcl` int,
	`rUcl` int,
	`rLcl` int,
	`outOfSpecCount` int NOT NULL DEFAULT 0,
	`outOfControlCount` int NOT NULL DEFAULT 0,
	`rule1Violations` int NOT NULL DEFAULT 0,
	`rule2Violations` int NOT NULL DEFAULT 0,
	`rule3Violations` int NOT NULL DEFAULT 0,
	`rule4Violations` int NOT NULL DEFAULT 0,
	`rule5Violations` int NOT NULL DEFAULT 0,
	`rule6Violations` int NOT NULL DEFAULT 0,
	`rule7Violations` int NOT NULL DEFAULT 0,
	`rule8Violations` int NOT NULL DEFAULT 0,
	`overallStatus` enum('excellent','good','acceptable','needs_improvement','critical') NOT NULL DEFAULT 'good',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `spc_summary_stats_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `spc_sampling_plans` ADD `mappingId` int;