CREATE TABLE `shift_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`shiftDate` timestamp NOT NULL,
	`shiftType` enum('morning','afternoon','night') NOT NULL,
	`shiftStart` timestamp NOT NULL,
	`shiftEnd` timestamp NOT NULL,
	`productionLineId` int,
	`machineId` int,
	`oee` decimal(5,2),
	`availability` decimal(5,2),
	`performance` decimal(5,2),
	`quality` decimal(5,2),
	`cpk` decimal(6,4),
	`cp` decimal(6,4),
	`ppk` decimal(6,4),
	`totalProduced` int DEFAULT 0,
	`goodCount` int DEFAULT 0,
	`defectCount` int DEFAULT 0,
	`plannedTime` int DEFAULT 0,
	`actualRunTime` int DEFAULT 0,
	`downtime` int DEFAULT 0,
	`alertCount` int DEFAULT 0,
	`spcViolationCount` int DEFAULT 0,
	`status` enum('generated','sent','failed') DEFAULT 'generated',
	`sentAt` timestamp,
	`sentTo` text,
	`reportContent` text,
	`reportFileUrl` varchar(500),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `shift_reports_id` PRIMARY KEY(`id`)
);
