CREATE TABLE `ai_ml_predictions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`prediction_id` varchar(64) NOT NULL,
	`model_id` varchar(64) NOT NULL,
	`model_name` varchar(100),
	`model_version` varchar(20),
	`prediction_type` varchar(50) NOT NULL,
	`input_data` text,
	`output_data` text,
	`confidence` decimal(5,4),
	`probability` decimal(5,4),
	`predicted_value` decimal(15,4),
	`actual_value` decimal(15,4),
	`error` decimal(15,4),
	`is_correct` int,
	`latency` int,
	`feature_importance` text,
	`explanation` text,
	`metadata` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ai_ml_predictions_id` PRIMARY KEY(`id`),
	CONSTRAINT `ai_ml_predictions_prediction_id_unique` UNIQUE(`prediction_id`)
);
--> statement-breakpoint
CREATE TABLE `analytics_cache` (
	`id` int AUTO_INCREMENT NOT NULL,
	`cache_key` varchar(255) NOT NULL,
	`cache_type` varchar(50) NOT NULL,
	`data` text NOT NULL,
	`computed_at` timestamp NOT NULL,
	`expires_at` timestamp NOT NULL,
	`hit_count` int NOT NULL DEFAULT 0,
	`last_accessed_at` timestamp,
	`metadata` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `analytics_cache_id` PRIMARY KEY(`id`),
	CONSTRAINT `analytics_cache_cache_key_unique` UNIQUE(`cache_key`)
);
--> statement-breakpoint
CREATE TABLE `batch_operation_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`operation_id` varchar(64) NOT NULL,
	`operation_type` varchar(50) NOT NULL,
	`status` enum('pending','running','completed','failed','cancelled') NOT NULL DEFAULT 'pending',
	`total_items` int NOT NULL DEFAULT 0,
	`processed_items` int NOT NULL DEFAULT 0,
	`success_items` int NOT NULL DEFAULT 0,
	`failed_items` int NOT NULL DEFAULT 0,
	`started_at` timestamp,
	`completed_at` timestamp,
	`user_id` int,
	`metadata` text,
	`error_message` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `batch_operation_logs_id` PRIMARY KEY(`id`),
	CONSTRAINT `batch_operation_logs_operation_id_unique` UNIQUE(`operation_id`)
);
--> statement-breakpoint
CREATE TABLE `error_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`error_id` varchar(64) NOT NULL,
	`error_type` varchar(100) NOT NULL,
	`error_code` varchar(50),
	`message` text NOT NULL,
	`stack_trace` text,
	`severity` enum('low','medium','high','critical') NOT NULL DEFAULT 'medium',
	`source` varchar(100),
	`user_id` int,
	`request_id` varchar(64),
	`request_path` varchar(500),
	`request_method` varchar(10),
	`user_agent` text,
	`ip_address` varchar(45),
	`metadata` text,
	`is_resolved` int NOT NULL DEFAULT 0,
	`resolved_at` timestamp,
	`resolved_by` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `error_logs_id` PRIMARY KEY(`id`),
	CONSTRAINT `error_logs_error_id_unique` UNIQUE(`error_id`)
);
--> statement-breakpoint
CREATE TABLE `iot_device_data` (
	`id` int AUTO_INCREMENT NOT NULL,
	`device_id` varchar(64) NOT NULL,
	`device_name` varchar(100),
	`device_type` varchar(50),
	`status` enum('online','offline','error','maintenance') NOT NULL DEFAULT 'offline',
	`last_seen` timestamp,
	`firmware_version` varchar(50),
	`ip_address` varchar(45),
	`mac_address` varchar(17),
	`location` varchar(255),
	`metrics` text,
	`temperature` decimal(5,2),
	`humidity` decimal(5,2),
	`pressure` decimal(8,2),
	`battery_level` int,
	`signal_strength` int,
	`error_count` int NOT NULL DEFAULT 0,
	`last_error` text,
	`metadata` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `iot_device_data_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `memory_leak_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`report_id` varchar(64) NOT NULL,
	`heap_used` bigint NOT NULL,
	`heap_total` bigint NOT NULL,
	`external` bigint,
	`array_buffers` bigint,
	`rss` bigint,
	`threshold` bigint,
	`leak_suspected` int NOT NULL DEFAULT 0,
	`growth_rate` decimal(10,4),
	`stack_trace` text,
	`process_id` varchar(50),
	`hostname` varchar(100),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `memory_leak_reports_id` PRIMARY KEY(`id`),
	CONSTRAINT `memory_leak_reports_report_id_unique` UNIQUE(`report_id`)
);
--> statement-breakpoint
CREATE TABLE `realtime_data_streams` (
	`id` int AUTO_INCREMENT NOT NULL,
	`stream_id` varchar(64) NOT NULL,
	`name` varchar(100) NOT NULL,
	`stream_type` enum('spc','oee','iot','system','security','ai') NOT NULL,
	`source` varchar(100) NOT NULL,
	`interval` int NOT NULL DEFAULT 5000,
	`is_active` int NOT NULL DEFAULT 0,
	`last_data_at` timestamp,
	`subscriber_count` int NOT NULL DEFAULT 0,
	`error_count` int NOT NULL DEFAULT 0,
	`config` text,
	`metadata` text,
	`created_by` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `realtime_data_streams_id` PRIMARY KEY(`id`),
	CONSTRAINT `realtime_data_streams_stream_id_unique` UNIQUE(`stream_id`)
);
--> statement-breakpoint
CREATE TABLE `security_audit_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`event_id` varchar(64) NOT NULL,
	`event_type` varchar(50) NOT NULL,
	`event_category` enum('authentication','authorization','data_access','configuration','system') NOT NULL DEFAULT 'system',
	`severity` enum('info','warning','error','critical') NOT NULL DEFAULT 'info',
	`user_id` int,
	`username` varchar(100),
	`ip_address` varchar(45),
	`user_agent` text,
	`resource` varchar(255),
	`action` varchar(50),
	`outcome` enum('success','failure','blocked') NOT NULL DEFAULT 'success',
	`details` text,
	`risk_score` int,
	`geo_location` varchar(100),
	`device_fingerprint` varchar(64),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `security_audit_logs_id` PRIMARY KEY(`id`),
	CONSTRAINT `security_audit_logs_event_id_unique` UNIQUE(`event_id`)
);
--> statement-breakpoint
CREATE TABLE `slow_query_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`query_hash` varchar(64) NOT NULL,
	`query_text` text NOT NULL,
	`execution_time` int NOT NULL,
	`rows_examined` int,
	`rows_returned` int,
	`connection_id` varchar(100),
	`user_id` int,
	`database_name` varchar(100),
	`table_name` varchar(100),
	`query_type` enum('SELECT','INSERT','UPDATE','DELETE','OTHER') DEFAULT 'SELECT',
	`is_optimized` int NOT NULL DEFAULT 0,
	`optimization_suggestion` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `slow_query_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `structured_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`log_id` varchar(64) NOT NULL,
	`level` enum('trace','debug','info','warn','error','fatal') NOT NULL DEFAULT 'info',
	`message` text NOT NULL,
	`category` varchar(50),
	`service` varchar(50),
	`trace_id` varchar(64),
	`span_id` varchar(64),
	`parent_span_id` varchar(64),
	`user_id` int,
	`session_id` varchar(64),
	`request_id` varchar(64),
	`duration` int,
	`metadata` text,
	`tags` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `structured_logs_id` PRIMARY KEY(`id`)
);
