import { useState } from "react";
import DashboardLayout from "@/components/DashboardLayout";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { FileText, Download, Calendar, Loader2, FileSpreadsheet, File, Check } from "lucide-react";
import { useLanguage } from "@/contexts/LanguageContext";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

type ReportType = "oee" | "spc" | "maintenance" | "combined";

interface ExportHistory {
  id: number;
  type: ReportType;
  format: "pdf" | "html" | "csv";
  dateRange: string;
  createdAt: Date;
  status: "completed" | "processing" | "failed";
}

const mockHistory: ExportHistory[] = [
  { id: 1, type: "oee", format: "pdf", dateRange: "01/12 - 15/12/2024", createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000), status: "completed" },
  { id: 2, type: "spc", format: "html", dateRange: "01/12 - 15/12/2024", createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000), status: "completed" },
  { id: 3, type: "maintenance", format: "csv", dateRange: "01/11 - 30/11/2024", createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000), status: "completed" },
];

export default function ExportReports() {
  const { language } = useLanguage();
  const [reportType, setReportType] = useState<ReportType>("oee");
  const [format, setFormat] = useState<"pdf" | "html" | "csv">("html");
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");
  const [isExporting, setIsExporting] = useState(false);
  const [includeCharts, setIncludeCharts] = useState(true);
  const [includeSummary, setIncludeSummary] = useState(true);
  const [includeDetails, setIncludeDetails] = useState(true);

  const handleExport = async () => {
    if (!startDate || !endDate) {
      toast.error(language === "vi" ? "Vui lòng chọn khoảng thời gian" : "Please select date range");
      return;
    }

    setIsExporting(true);
    
    // Simulate export process
    setTimeout(() => {
      setIsExporting(false);
      toast.success(language === "vi" ? "Xuất báo cáo thành công!" : "Report exported successfully!");
      
      // Create and download the file
      const content = generateSampleReport(reportType, startDate, endDate);
      const blob = new Blob([content], { type: format === "html" ? "text/html" : "text/plain" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `report_${reportType}_${startDate}_${endDate}.${format}`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }, 2000);
  };

  const generateSampleReport = (type: ReportType, start: string, end: string): string => {
    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${type.toUpperCase()} Report</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; }
    h1 { color: #1e40af; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { padding: 12px; border: 1px solid #e5e7eb; text-align: left; }
    th { background: #f3f4f6; }
  </style>
</head>
<body>
  <h1>${type.toUpperCase()} Report</h1>
  <p>Date Range: ${start} - ${end}</p>
  <p>Generated: ${new Date().toLocaleString('vi-VN')}</p>
  
  <h2>Summary</h2>
  <table>
    <tr><th>Metric</th><th>Value</th></tr>
    <tr><td>Average OEE</td><td>85.2%</td></tr>
    <tr><td>Total Records</td><td>156</td></tr>
  </table>
  
  <p>Report generated by SPC/CPK Calculator</p>
</body>
</html>
    `;
  };

  const getTypeLabel = (type: ReportType) => {
    const labels: Record<ReportType, { vi: string; en: string }> = {
      oee: { vi: "Báo cáo OEE", en: "OEE Report" },
      spc: { vi: "Báo cáo SPC/CPK", en: "SPC/CPK Report" },
      maintenance: { vi: "Báo cáo Bảo trì", en: "Maintenance Report" },
      combined: { vi: "Báo cáo Tổng hợp", en: "Combined Report" },
    };
    return labels[type][language === "vi" ? "vi" : "en"];
  };

  const getFormatIcon = (fmt: string) => {
    switch (fmt) {
      case "pdf": return <File className="h-4 w-4 text-red-500" />;
      case "html": return <FileText className="h-4 w-4 text-blue-500" />;
      case "csv": return <FileSpreadsheet className="h-4 w-4 text-green-500" />;
      default: return <FileText className="h-4 w-4" />;
    }
  };

  return (
    <DashboardLayout>
      <div className="container py-6 space-y-6">
        <div>
          <h1 className="text-2xl font-bold">
            {language === "vi" ? "Xuất Báo cáo" : "Export Reports"}
          </h1>
          <p className="text-muted-foreground">
            {language === "vi" 
              ? "Tạo và tải xuống báo cáo OEE, SPC, và Bảo trì" 
              : "Generate and download OEE, SPC, and Maintenance reports"}
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Export Form */}
          <div className="lg:col-span-2">
            <Card>
              <CardHeader>
                <CardTitle>{language === "vi" ? "Tạo Báo cáo Mới" : "Create New Report"}</CardTitle>
                <CardDescription>
                  {language === "vi" 
                    ? "Chọn loại báo cáo và khoảng thời gian" 
                    : "Select report type and date range"}
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-6">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label>{language === "vi" ? "Loại báo cáo" : "Report Type"}</Label>
                    <Select value={reportType} onValueChange={(v: ReportType) => setReportType(v)}>
                      <SelectTrigger>
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="oee">{language === "vi" ? "Báo cáo OEE" : "OEE Report"}</SelectItem>
                        <SelectItem value="spc">{language === "vi" ? "Báo cáo SPC/CPK" : "SPC/CPK Report"}</SelectItem>
                        <SelectItem value="maintenance">{language === "vi" ? "Báo cáo Bảo trì" : "Maintenance Report"}</SelectItem>
                        <SelectItem value="combined">{language === "vi" ? "Báo cáo Tổng hợp" : "Combined Report"}</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  <div className="space-y-2">
                    <Label>{language === "vi" ? "Định dạng" : "Format"}</Label>
                    <Select value={format} onValueChange={(v: any) => setFormat(v)}>
                      <SelectTrigger>
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="html">HTML</SelectItem>
                        <SelectItem value="pdf">PDF</SelectItem>
                        <SelectItem value="csv">CSV</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label>{language === "vi" ? "Từ ngày" : "Start Date"}</Label>
                    <Input 
                      type="date" 
                      value={startDate} 
                      onChange={(e) => setStartDate(e.target.value)} 
                    />
                  </div>
                  <div className="space-y-2">
                    <Label>{language === "vi" ? "Đến ngày" : "End Date"}</Label>
                    <Input 
                      type="date" 
                      value={endDate} 
                      onChange={(e) => setEndDate(e.target.value)} 
                    />
                  </div>
                </div>

                <div className="space-y-4">
                  <Label>{language === "vi" ? "Nội dung báo cáo" : "Report Content"}</Label>
                  <div className="space-y-2">
                    <div className="flex items-center space-x-2">
                      <Checkbox 
                        id="summary" 
                        checked={includeSummary} 
                        onCheckedChange={(c) => setIncludeSummary(!!c)} 
                      />
                      <label htmlFor="summary" className="text-sm">
                        {language === "vi" ? "Bao gồm tổng quan" : "Include summary"}
                      </label>
                    </div>
                    <div className="flex items-center space-x-2">
                      <Checkbox 
                        id="charts" 
                        checked={includeCharts} 
                        onCheckedChange={(c) => setIncludeCharts(!!c)} 
                      />
                      <label htmlFor="charts" className="text-sm">
                        {language === "vi" ? "Bao gồm biểu đồ" : "Include charts"}
                      </label>
                    </div>
                    <div className="flex items-center space-x-2">
                      <Checkbox 
                        id="details" 
                        checked={includeDetails} 
                        onCheckedChange={(c) => setIncludeDetails(!!c)} 
                      />
                      <label htmlFor="details" className="text-sm">
                        {language === "vi" ? "Bao gồm chi tiết" : "Include details"}
                      </label>
                    </div>
                  </div>
                </div>

                <Button 
                  className="w-full" 
                  onClick={handleExport} 
                  disabled={isExporting}
                >
                  {isExporting ? (
                    <>
                      <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                      {language === "vi" ? "Đang xuất..." : "Exporting..."}
                    </>
                  ) : (
                    <>
                      <Download className="h-4 w-4 mr-2" />
                      {language === "vi" ? "Xuất Báo cáo" : "Export Report"}
                    </>
                  )}
                </Button>
              </CardContent>
            </Card>
          </div>

          {/* Quick Export */}
          <div className="space-y-4">
            <Card>
              <CardHeader>
                <CardTitle>{language === "vi" ? "Xuất Nhanh" : "Quick Export"}</CardTitle>
              </CardHeader>
              <CardContent className="space-y-2">
                {[
                  { label: language === "vi" ? "OEE hôm nay" : "Today's OEE", type: "oee" as ReportType },
                  { label: language === "vi" ? "OEE tuần này" : "This Week OEE", type: "oee" as ReportType },
                  { label: language === "vi" ? "SPC tháng này" : "This Month SPC", type: "spc" as ReportType },
                  { label: language === "vi" ? "Bảo trì tháng này" : "This Month Maintenance", type: "maintenance" as ReportType },
                ].map((item, index) => (
                  <Button 
                    key={index} 
                    variant="outline" 
                    className="w-full justify-start"
                    onClick={() => {
                      toast.success(language === "vi" ? `Đang xuất ${item.label}...` : `Exporting ${item.label}...`);
                    }}
                  >
                    <Download className="h-4 w-4 mr-2" />
                    {item.label}
                  </Button>
                ))}
              </CardContent>
            </Card>
          </div>
        </div>

        {/* Export History */}
        <Card>
          <CardHeader>
            <CardTitle>{language === "vi" ? "Lịch sử Xuất" : "Export History"}</CardTitle>
            <CardDescription>
              {language === "vi" ? "Các báo cáo đã xuất gần đây" : "Recently exported reports"}
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-2">
              {mockHistory.map((item) => (
                <div 
                  key={item.id} 
                  className="flex items-center justify-between p-3 bg-muted/50 rounded-lg"
                >
                  <div className="flex items-center gap-3">
                    {getFormatIcon(item.format)}
                    <div>
                      <p className="font-medium">{getTypeLabel(item.type)}</p>
                      <p className="text-sm text-muted-foreground">
                        {item.dateRange} • {item.createdAt.toLocaleString('vi-VN')}
                      </p>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <Badge variant={item.status === "completed" ? "default" : "secondary"}>
                      {item.status === "completed" && <Check className="h-3 w-3 mr-1" />}
                      {item.format.toUpperCase()}
                    </Badge>
                    <Button variant="ghost" size="icon">
                      <Download className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>
    </DashboardLayout>
  );
}
